# Python stubs generated by omniidl from caesar.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "Caesar"
#
__name__ = "Caesar"
_0_Caesar = omniORB.openModule("Caesar", r"caesar.idl")
_0_Caesar__POA = omniORB.openModule("Caesar__POA", r"caesar.idl")


# interface CaesarCipher
_0_Caesar._d_CaesarCipher = (omniORB.tcInternal.tv_objref, "IDL:Caesar/CaesarCipher:1.0", "CaesarCipher")
omniORB.typeMapping["IDL:Caesar/CaesarCipher:1.0"] = _0_Caesar._d_CaesarCipher
_0_Caesar.CaesarCipher = omniORB.newEmptyClass()
class CaesarCipher :
    _NP_RepositoryId = _0_Caesar._d_CaesarCipher[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Caesar.CaesarCipher = CaesarCipher
_0_Caesar._tc_CaesarCipher = omniORB.tcInternal.createTypeCode(_0_Caesar._d_CaesarCipher)
omniORB.registerType(CaesarCipher._NP_RepositoryId, _0_Caesar._d_CaesarCipher, _0_Caesar._tc_CaesarCipher)

# CaesarCipher operations and attributes
CaesarCipher._d_encode = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
CaesarCipher._d_decode = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)

# CaesarCipher object reference
class _objref_CaesarCipher (CORBA.Object):
    _NP_RepositoryId = CaesarCipher._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def encode(self, *args):
        return _omnipy.invoke(self, "encode", _0_Caesar.CaesarCipher._d_encode, args)

    def decode(self, *args):
        return _omnipy.invoke(self, "decode", _0_Caesar.CaesarCipher._d_decode, args)

    __methods__ = ["encode", "decode"] + CORBA.Object.__methods__

omniORB.registerObjref(CaesarCipher._NP_RepositoryId, _objref_CaesarCipher)
_0_Caesar._objref_CaesarCipher = _objref_CaesarCipher
del CaesarCipher, _objref_CaesarCipher

# CaesarCipher skeleton
__name__ = "Caesar__POA"
class CaesarCipher (PortableServer.Servant):
    _NP_RepositoryId = _0_Caesar.CaesarCipher._NP_RepositoryId


    _omni_op_d = {"encode": _0_Caesar.CaesarCipher._d_encode, "decode": _0_Caesar.CaesarCipher._d_decode}

CaesarCipher._omni_skeleton = CaesarCipher
_0_Caesar__POA.CaesarCipher = CaesarCipher
omniORB.registerSkeleton(CaesarCipher._NP_RepositoryId, CaesarCipher)
del CaesarCipher
__name__ = "Caesar"

#
# End of module "Caesar"
#
__name__ = "caesar_idl"

_exported_modules = ( "Caesar", )

# The end.
