# DO NOT EDIT THIS FILE!
#
# Python module Caesar__POA generated by omniidl

import omniORB
omniORB.updateModule("Caesar__POA")

# ** 1. Stub files contributing to this module
import caesar_idl

# ** 2. Sub-modules

# ** 3. End
